name: Trivy Scan

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy Table Report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: python:3.11-slim
          format: table
          output: results.txt
          exit-code: 0
          severity: CRITICAL,HIGH,MEDIUM,LOW
          ignore-unfixed: false

      - name: Run Trivy JSON Report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: python:3.11-slim
          format: json
          output: results.json
          exit-code: 0
          severity: CRITICAL,HIGH,MEDIUM,LOW
          ignore-unfixed: false

      - name: Upload Trivy Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            results.txt
            results.json
